"""
Do Not Edit this file. You may and are encouraged to look at it for reference.
"""

import unittest
import gas_mileage


class TestCreateNotebook(unittest.TestCase):
    def test001_createIndexExists(self):
        self.assertTrue('createNotebook' in dir(gas_mileage),
                        'Function "createNotebook" is not defined, check your spelling')
        return

    def test002_createNotebookReturnsList(self):
        actual = gas_mileage.createNotebook()
        self.assertTrue(type(actual) is list,
            'Function "createNotebook" did not return a list but instead a %s' % type(actual))
        return

    def test003_createNotebookReturnsEmptyList(self):
        actual = gas_mileage.createNotebook()
        self.assertEqual(0, len(actual), 'The list should have no items in it')
        return

if __name__ == '__main__':
    unittest.main()
