"""
Do Not Edit this file. You may and are encouraged to look at it for reference.
"""

import unittest
import re
import gas_mileage


class TestListTrips(unittest.TestCase):
    def verifyLines(self, notebook, mpg):
        from gas_mileage import listTrips

        trips = listTrips(notebook)
        self.assertTrue(type(trips) is list, 'listTrips did not return a list')
        self.assertTrue(len(trips) == len(notebook))

        for i in range(len(trips)):
            nb = notebook[i]

            matchdate = nb['date']
            matchmiles = str(nb['miles']) + ' miles'
            matchgallons = str(nb['gallons']) + ' gallons'
            matchmpg = str(mpg[i]) + ' mpg'

            trip = trips[i]

            self.assertTrue(matchdate.lower() in trip.lower(), '"' + nb['date'] + '" not found in "' + trip + '"')
            self.assertTrue(matchmiles.lower() in trip.lower(),
                            '"' + str(nb['miles']) + ' miles" not found in "' + trip + '"')
            self.assertTrue(matchgallons.lower() in trip.lower(),
                            '"' + str(nb['gallons']) + ' gallons" not found in "' + trip + '"')
            self.assertTrue(matchmpg.lower() in trip.lower(), '"' + str(mpg[i]) + ' MPG" not found in "' + trip + '"')


    def test001_listTripsExists(self):
        self.assertTrue('listTrips' in dir(gas_mileage),
                        'Function "listTrips" is not defined, check your spelling')
        return


    def test002_listTripsEmptyNotebook(self):
        from gas_mileage import listTrips
        notebook = []
        lines = listTrips(notebook)
        self.assertTrue(type(lines) is list, 'listTrips did not return a list')
        self.assertTrue(len(lines) == 0, 'There were no trips but you returned lines')


    def test003_listTrips(self):
        notebook = [
            {'date': '01/01/2017', 'miles': 300.0, 'gallons': 10.0},
            {'date': '01/05/2017', 'miles': 182.0, 'gallons': 7.0},
            {'date': '01/15/2017', 'miles': 240.0, 'gallons': 9.6}
        ]
        mpg = [30.0, 26.0, 25.0]
        self.verifyLines(notebook, mpg)


    def test004_listTrips(self):
        notebook = [
            {'date': 'Jan 01', 'miles': 45.0, 'gallons': 1.5},
            {'date': 'Jan 05', 'miles': 405.0, 'gallons': 15.0}
        ]
        mpg = [30.0, 27.0]
        self.verifyLines(notebook, mpg)


if __name__ == '__main__':
    unittest.main()
