"""
Do Not Edit this file. You may and are encouraged to look at it for reference.
"""

import unittest
import gas_mileage


class TestFormatMenuPrompt(unittest.TestCase):
    def test001_formatMenuPromptExists(self):
        self.assertTrue('formatMenuPrompt' in dir(gas_mileage),
                        'Function "formatMenuPrompt" is not defined, check your spelling')
        return

    def test002_formatMenuPromptReturnsCorrectString(self):
        expected = "Enter an option: "
        actual = gas_mileage.formatMenuPrompt()
        self.assertEqual(actual, expected)


if __name__ == '__main__':
    unittest.main()
