"""
Do Not Edit this file. You may and are encouraged to look at it for reference.
"""

import re
import unittest

import gas_mileage


class TestFormatMenu(unittest.TestCase):
    def test001_formatMenuExists(self):
        self.assertTrue('formatMenu' in dir(gas_mileage),
                        'Function "formatMenu" is not defined, check your spelling')
        return

    def test002_formatMenuContainsAllActions(self):
        actual = gas_mileage.formatMenu()
        self.assertTrue(type(actual) is list, 'formatMenu did not return a list')

        expected = [
            "\[r\]",
            "\[l\]",
            "\[c\]",
            "\[q\]",
        ]
        for expected_line in expected:
            found = False
            for actual_line in actual:
                if re.search(expected_line.lower(), actual_line.lower()):
                    found = True
                    break
            self.assertTrue(found, "'" + expected_line + "' not found in formatMenu return")


if __name__ == '__main__':
    unittest.main()
