"""
Do Not Edit this file. You may and are encouraged to look at it for reference.
Do Not Move on to the next function until its tests report 'ok' or your code
may not work as expected.
"""

import unittest
from test_createIndex import test_createIndex
from test_recordBook import test_recordBook
from test_findBook import test_findBook
from test_listBooks import test_listBooks
from test_formatMenu import test_formatMenu
from test_formatMenuPrompt import test_formatMenuPrompt
from test_getUserChoice import test_getUserChoice
from test_getISBN import test_getISBN
from test_getTitle import test_getTitle
from test_recordBookAction import test_recordBookAction
from test_findBookAction import test_findBookAction
from test_listBooksAction import test_listBooksAction
from test_quitAction import test_quitAction
from test_applyAction import test_applyAction

if __name__ == '__main__':
    testCases = [
        test_createIndex,
        test_recordBook,
        test_findBook,
        test_listBooks,
        test_formatMenu,
        test_formatMenuPrompt,
        test_getUserChoice,
        test_getISBN,
        test_getTitle,
        test_recordBookAction,
        test_findBookAction,
        test_listBooksAction,
        test_quitAction,
        test_applyAction,
    ]

    allTests = [ ]
    for testCase in testCases:
        allTests.append( unittest.TestLoader( ).loadTestsFromTestCase( testCase ) )

    unittest.TextTestRunner( ).run( unittest.TestSuite( allTests ) )
