"""
Do Not Edit this file. You may and are encouraged to look at it for reference.
"""

import unittest
import dnaSequencing

class TestJoinTwoStrands(unittest.TestCase):
    def test001_joinTwoStrandsExists(self):
        self.assertTrue('joinTwoStrands' in dir(dnaSequencing),
                        'Function "joinTwoStrands" was not defined, check your spelling')

    def test002_runJoinTwoStrands1(self):
        from dnaSequencing import joinTwoStrands
        self.assertEqual(joinTwoStrands('abcdefg', 'defgabc', 4), 'abcdefgabc',
                         'Check your output target="abcdefg", candidate="defgabc", overlap=4')

    def test003_runJoinTwoStrands2(self):
        from dnaSequencing import joinTwoStrands
        self.assertEqual(joinTwoStrands('abcdefg', '', 0), 'abcdefg',
                         'Check your output target="abcdefg", candidate="", overlap=0')

    def test004_runJoinTwoStrands3(self):
        from dnaSequencing import joinTwoStrands
        self.assertEqual(joinTwoStrands('GTCGCGTTCAGGCGCATTAAGTTAGTCGGA', 'TCGCGTTCAGGCGCATTAAGTTAGTCGGAG', 29),
                         'GTCGCGTTCAGGCGCATTAAGTTAGTCGGAG',
                         'Check your output target="GTCGCGTTCAGGCGCATTAAGTTAGTCGGA", candidate="TCGCGTTCAGGCGCATTAAGTTAGTCGGAG", overlap=29')

    def test005_runJoinTwoStrands4(self):
        from dnaSequencing import joinTwoStrands
        self.assertEqual(joinTwoStrands('ABCDEFG', 'CDEFGHH', 5), 'ABCDEFGHH',
                         'Check your output target="ABCDEFG", candidate="CDEFGHH", overlap=5')

if __name__ == '__main__':
    unittest.main()
